name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure Git Credentials
      - name: Configure Git Credentials
        uses: actions/checkout@v4

      # Step 2: Configure Git user
      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Cache dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: mkdocs-material-${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            mkdocs-material-${{ runner.os }}-pip-

      # Step 4: Build the site
      - name: Build MkDocs site
        run: mkdocs build

      # Step 5: Deploy the site
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 6: Upload the site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Notify
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
